name: Semgrep SAST

on:
  push:

jobs:
  semgrep-scan:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: |
          docker run --rm -v "${PWD}:/src" semgrep/semgrep semgrep scan --config auto
